# Generated by Django 5.0.4 on 2024-04-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stability_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('working', 'WORKING'), ('success', 'SUCCESS'), ('error', 'ERROR'), ('pending', 'PENDING'), ('none', 'NONE')], default='none', max_length=9),
        ),
    ]
